### ISSUE TITLE
Bug in error logging of stream writer

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#190]
When something goes wrong, it doesn't tell you anything useful like what stream it was trying to open and any details that might help fix it.

```
2022 Jun  9, 16:51:18.343 Engine 'sql': moodle_exception: error/[[unable_to_open_stream]] in /var/www/moodle.local/admin/tool/dataflows/classes/local/step/writer_stream.php:103
Stack trace:
#0 /var/www/moodle.local/admin/tool/dataflows/classes/local/step/writer_stream.php(94): class@anonymous->__construct()
#1 /var/www/moodle.local/admin/tool/dataflows/classes/local/execution/flow_engine_step.php(59): tool_dataflows\local\step\writer_stream->get_iterator()
#2 /var/www/moodle.local/admin/tool/dataflows/classes/local/execution/engine.php(203): tool_dataflows\local\execution\flow_engine_step->go()
#3 /var/www/moodle.local/admin/tool/dataflows/classes/local/execution/engine.php(180): tool_dataflows\local\execution\engine->execute_step()
#4 /var/www/moodle.local/admin/tool/dataflows/run.php(109): tool_dataflows\local\execution\engine->execute()
#5 {main} 
```

Also I think we can improve the way this behaves. If a file can't be written, I would consider this a 'normal' error in that it is the kinda of thing you would typically hit while authoring a flow, or even hit while in production and when something in the inf changes under you.The stack trace might be helpful now but is pretty low value in terms of trying to fix the config of the flow. ie it isn't a code level bug. I would prefer it if in this case for example the step itself emitted a log with something useful and then aborted.

**Comment by brendanheywood** [comment]
Note in this case the permissions were wrong on the folder I was writing to
