### ISSUE TITLE
Bug misleading error when parsing expressions

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#206]
This workflow explodes with a misleading error:

```
2022 Jun 16, 09:30:09.497 Engine 'Delta export of users', step 'SQL reader': status Waiting 
2022 Jun 16, 09:30:09.497 Engine 'Delta export of users', step 'Every hour': status Finished 
2022 Jun 16, 09:30:09.523 Issue parsing ${{config.num}} - Variable "config" is not valid around position 1 for expression `config.num`. 
2022 Jun 16, 09:30:09.523 Engine 'Delta export of users': Aborted: Variable "config" is not valid around position 1 for expression `config.num`. 
2022 Jun 16, 09:30:09.523 Engine 'Delta export of users': Symfony\Component\ExpressionLanguage\SyntaxError: Variable "config" is not valid around position 1 for expression `config.num`. in /var/www/moodle.local/admin/tool/dataflows/vendor/symfony/expression-language/Parser.php:204
```

1) First the error on line 3 doesn't mention the step, and the step before it is 'Every hour' but the error in in 'SQL reader'
2) Second it says 'is not valid around position 1' but position 1 doesn't seem to correlate with where the expression is which is on line 2 character 21. I assume this is the position within the string 'config.num' rather than the sql string.

[Delta_export_of_users_20220615_2331.yml.txt](https://github.com/catalyst/moodle-tool_dataflows/files/8914148/Delta_export_of_users_20220615_2331.yml.txt)

**Comment by keevan** [comment]
Yes to both. I've been working on updating the expressions handling so I'll also take this into account and see if this can be adjusted as well. It's very much in the bits I've touched.

**Comment by keevan** [comment]
I've retested this in the current state. This is the output:

Given this workflow:  [Delta_export_of_users_20220701_0410.yml (copy).txt](https://github.com/catalyst/moodle-tool_dataflows/files/9025001/Delta_export_of_users_20220701_0410.yml.copy.txt) (note I've removed the cron trigger step as it's has changed since)

```
2022 Jul  1, 14:10:13.545 Engine "Delta export of users": status: new 
2022 Jul  1, 14:10:13.553 Engine "Delta export of users", step "SQL reader": status: new 
2022 Jul  1, 14:10:13.553 Engine "Delta export of users", step "write to csv": status: new 
2022 Jul  1, 14:10:13.556 Engine "Delta export of users", step "SQL reader": status: initialised 
2022 Jul  1, 14:10:13.556 Engine "Delta export of users", step "write to csv": status: initialised 
2022 Jul  1, 14:10:13.556 Engine "Delta export of users": status: initialised, config: {"isdryrun":false} 
2022 Jul  1, 14:10:13.593 Engine "Delta export of users": status: processing 
2022 Jul  1, 14:10:13.594 Engine "Delta export of users", step "write to csv": status: waiting 
2022 Jul  1, 14:10:13.654 Engine "Delta export of users", step "SQL reader": Variable "config" is not valid around position 1 for expression `config.num`.. for expression SELECT generate_series AS num
FROM generate_series(${{config.num}}, ${{config.num}} + 3)
 
2022 Jul  1, 14:10:13.655 Engine "Delta export of users", step "SQL reader": status: aborted 
2022 Jul  1, 14:10:13.655 Engine "Delta export of users": status: aborted 
2022 Jul  1, 14:10:13.655 Engine "Delta export of users": Aborted: Variable "config" is not valid around position 1 for expression `config.num`. 
2022 Jul  1, 14:10:13.655 Engine "Delta export of users": Symfony\Component\ExpressionLanguage\SyntaxError: Variable "config" is not valid around position 1 for expression `config.num`. in /var/www/moodle/admin/tool/dataflows/vendor/symfony/expression-language/Parser.php:204
Stack trace:
#0 /var/www/moodle/admin/tool/dataflows/vendor/symfony/expression-language/Parser.php(149): Symfony\Component\ExpressionLanguage\Parser->parsePrimaryExpression()
#1 /var/www/moodle/admin/tool/dataflows/vendor/symfony/expression-language/Parser.php(110): Symfony\Component\ExpressionLanguage\Parser->getPrimary()
#2 /var/www/moodle/admin/tool/dataflows/vendor/symfony/expression-language/Parser.php(100): Symfony\Component\ExpressionLanguage\Parser->parseExpression()
#3 /var/www/moodle/admin/tool/dataflows/vendor/symfony/expression-language/ExpressionLanguage.php(105): Symfony\Component\ExpressionLanguage\Parser->parse(Object(Symfony\Component\ExpressionLanguage\TokenStream), Array)
#4 /var/www/moodle/admin/tool/dataflows/vendor/symfony/expression-language/ExpressionLanguage.php(78): Symfony\Component\ExpressionLanguage\ExpressionLanguage->parse('config.num', Array)
#5 /var/www/moodle/admin/tool/dataflows/classes/parser.php(94): Symfony\Component\ExpressionLanguage\ExpressionLanguage->evaluate('config.num', Array)
#6 /var/www/moodle/admin/tool/dataflows/classes/parser.php(59): tool_dataflows\parser->internal_evaluator('SELECT generate...', Array, Object(Closure))
#7 /var/www/moodle/admin/tool/dataflows/classes/local/step/reader_sql.php(160): tool_dataflows\parser->evaluate_or_fail('SELECT generate...', Array, Object(Closure))
#8 /var/www/moodle/admin/tool/dataflows/classes/local/step/reader_sql.php(54): tool_dataflows\local\step\reader_sql->construct_query()
#9 /var/www/moodle/admin/tool/dataflows/classes/local/execution/flow_engine_step.php(59): tool_dataflows\local\step\reader_sql->get_iterator(Object(tool_dataflows\local\execution\flow_engine_step))
#10 /var/www/moodle/admin/tool/dataflows/classes/local/execution/engine.php(250): tool_dataflows\local\execution\flow_engine_step->go()
#11 /var/www/moodle/admin/tool/dataflows/classes/local/execution/engine.php(217): tool_dataflows\local\execution\engine->execute_step()
#12 /var/www/moodle/admin/tool/dataflows/run.php(109): tool_dataflows\local\execution\engine->execute()
#13 {main} 
```

It's slightly better (step context wise), but the position 1 might throw the user off. I'll make some adjustments to pinpoint the location of the affected issue. Noting that this might not necessarily work for nested expressions "maybe" without adding some complexity, but I think we'll deal with that once/if we hit that - as it might just work after the changes I have in mind.
