### ISSUE TITLE
writer_stream step closing issues near the end of the output

### ISSUE THREAD

**Issue by keevan** [catalyst/moodle-tool_dataflows#329]
Example workflow attached

[read_write_20220721_0921.yml.txt](https://github.com/catalyst/moodle-tool_dataflows/files/9158055/read_write_20220721_0921.yml.txt)

```
2022 Jul 21, 19:20:31.387 Engine "read write", step "sql": status: finished 


Warning:  fwrite(): supplied resource is not a valid stream resource in /var/www/moodle/admin/tool/dataflows/classes/local/step/writer_stream.php on line 161

2022 Jul 21, 19:20:31.388 Engine "read write", step "writer": fwrite(): supplied resource is not a valid stream resource 
2022 Jul 21, 19:20:31.388 Engine "read write": moodle_exception: error/Failed to write to stream "/tmp/output.json". in /var/www/moodle/admin/tool/dataflows/classes/local/step/writer_stream.php:163
Stack trace:
#0 /var/www/moodle/admin/tool/dataflows/classes/local/execution/iterators/dataflow_iterator.php(86): class@anonymous->on_abort()
#1 /var/www/moodle/admin/tool/dataflows/classes/local/execution/flow_engine_step.php(46): tool_dataflows\local\execution\iterators\dataflow_iterator->abort()
#2 /var/www/moodle/admin/tool/dataflows/classes/local/execution/engine.php(327): tool_dataflows\local\execution\flow_engine_step->abort()
#3 /var/www/moodle/admin/tool/dataflows/classes/local/execution/engine.php(309): tool_dataflows\local\execution\engine->abort(Object(dml_exception))
#4 /var/www/moodle/admin/tool/dataflows/classes/local/execution/engine.php(259): tool_dataflows\local\execution\engine->finalise()
#5 /var/www/moodle/admin/tool/dataflows/run.php(109): tool_dataflows\local\execution\engine->execute()
#6 {main} 
```

**Comment by jaypha** [comment]
I have not been able to reproduce this error. Can you provide more context?

**Comment by jaypha** [comment]
I have run it on master, and I'm afraid I am still not able to reproduce this error.

**Comment by keevan** [comment]
This might be related to this, which the fix has been landed for https://github.com/catalyst/moodle-tool_dataflows/issues/339

I'll give this a retest and will close if it's no longer an issue.
