### ISSUE TITLE
Bug ERROR: Mixed types of sql query parameters

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#447]
```
2022 Aug 4, 19:24:19.113 Engine "dataflow": status: new
--- then several hundred lines of the same error listed before, then ---
2022 Aug 4, 19:24:22.087 Engine "dataflow", step "drop or enrol": status: aborted
2022 Aug 4, 19:24:22.087 Engine "dataflow": Aborted: ERROR: Mixed types of sql query parameters!!
2022 Aug 4, 19:24:22.087 Engine "dataflow", step "json read": status: finished
2022 Aug 4, 19:24:22.088 Engine "dataflow", step "get course details": status: finished
2022 Aug 4, 19:24:22.088 Engine "dataflow", step "get users WS": status: finished
2022 Aug 4, 19:24:22.090 Engine "dataflow": status: aborted
2022 Aug 4, 19:24:22.091 Engine "dataflow": dml_exception: ERROR: Mixed types of sql query parameters!! in /home/moodle/public/lib/dml/moodle_database.php:915
Stack trace:
#0 /home/moodle/public/lib/dml/mysqli_native_moodle_database.php(1268): moodle_database->fix_sql_params()
#1 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(293): mysqli_native_moodle_database->get_records_sql()
#2 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(120): tool_dataflows\dataflow->get_edges()
#3 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(470): tool_dataflows\dataflow->__get()
#4 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(120): tool_dataflows\dataflow->get_step_order()
#5 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(449): tool_dataflows\dataflow->__get()
#6 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(120): tool_dataflows\dataflow->get_steps()
#7 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(147): tool_dataflows\dataflow->__get()
#8 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(120): tool_dataflows\dataflow->get_variables()
#9 /home/moodle/public/admin/tool/dataflows/classes/step.php(153): tool_dataflows\dataflow->__get()
#10 /home/moodle/public/admin/tool/dataflows/classes/step.php(126): tool_dataflows\step->get_variables()
#11 /home/moodle/public/admin/tool/dataflows/classes/step.php(244): tool_dataflows\step->__get()
#12 /home/moodle/public/admin/tool/dataflows/classes/step.php(126): tool_dataflows\step->get_config()
#13 /home/moodle/public/admin/tool/dataflows/classes/local/step/flow_logic_case.php(159): tool_dataflows\step->__get()
#14 /home/moodle/public/admin/tool/dataflows/classes/local/step/flow_logic_case.php(140): tool_dataflows\local\execution\iterators\dataflow_iterator@anonymous->__construct()
#15 /home/moodle/public/admin/tool/dataflows/classes/local/execution/flow_engine_step.php(59): tool_dataflows\local\step\flow_logic_case->get_iterator()
#16 /home/moodle/public/admin/tool/dataflows/classes/local/execution/engine.php(418): tool_dataflows\local\execution\flow_engine_step->go()
#17 /home/moodle/public/admin/tool/dataflows/classes/local/execution/engine.php(373): tool_dataflows\local\execution\engine->execute_step()
#18 /home/moodle/public/admin/tool/dataflows/run.php(109): tool_dataflows\local\execution\engine->execute()
#19 {main}
```

**Comment by brendanheywood** [comment]
This might be a mysqli related issue

**Comment by jaypha** [comment]
Could you give me the original flow that caused this error, as well as the full output? Thanks.

**Comment by jaypha** [comment]
So far I have not been able to reproduce this problem. The complaint is that the SQL use a mixture of parametised input where only one type is allowed (Namely '?' mixed with '$*').
Upon examining the offending SQL in the code, I am unable to find how it could cause this error.

**Comment by brendanheywood** [comment]
Lets kill this then until we have better repro steps
